//=====================================================================================================================
//
// ideMobi copyright 2017 
// All rights reserved by ideMobi
//
//=====================================================================================================================
using BasicToolBox;
//=====================================================================================================================
namespace NetWorkedData
{
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    public partial class NWDAccountConsent : NWDBasis<NWDAccountConsent>
    {
        //-------------------------------------------------------------------------------------------------------------
        public NWDAccountConsent()
        {
            //Debug.Log("NWDUserConsent Constructor");
        }
        //-------------------------------------------------------------------------------------------------------------
        public NWDAccountConsent(bool sInsertInNetWorkedData) : base(sInsertInNetWorkedData)
        {
            //Debug.Log("NWDUserConsent Constructor with sInsertInNetWorkedData : " + sInsertInNetWorkedData.ToString() + "");
        }
        //-------------------------------------------------------------------------------------------------------------
        public bool ConsentIsValid()
        {
            bool rReturn = true;
            NWDConsent tAppConsent = Consent.GetObject();
            if (tAppConsent != null)
            {
                switch (Consent.GetObject().ExpectedState)
                {
                    case BTBSwitchState.On:
                        {
                            if (Authorization != BTBSwitchState.On)
                            {
                                rReturn = false;
                                break;
                            }
                        }
                        break;
                    case BTBSwitchState.Off:
                        {
                            if (Authorization != BTBSwitchState.Off)
                            {
                                rReturn = false;
                                break;
                            }
                        }
                        break;
                    case BTBSwitchState.Unknow:
                        {
                            // no necessary spect
                        }
                        break;
                }
            }
            return rReturn;
        }
        //-------------------------------------------------------------------------------------------------------------
        public static NWDAccountConsent ForConsent(NWDConsent sAppConsent, bool sCreateIfNull = true)
        {
            NWDAccountConsent rUserConsent = null;
            foreach (NWDAccountConsent tAuthorization in FindDatas())
            {
                if (tAuthorization.Consent.GetObject() == sAppConsent && tAuthorization.Version.GetValue() == sAppConsent.Version.GetValue())
                {
                    rUserConsent = tAuthorization;
                    break;
                }
            }

            if (rUserConsent == null && sCreateIfNull)
            {
                rUserConsent = NewData();
                #if UNITY_EDITOR
                rUserConsent.InternalKey = sAppConsent.InternalKey;
                rUserConsent.InternalDescription = NWDAccountNickname.GetNickname() + " - " + sAppConsent.Version;
                #endif
                rUserConsent.Tag = NWDBasisTag.TagUserCreated; // Data generated by User-created
                rUserConsent.Consent.SetReference(sAppConsent.Reference);
                rUserConsent.Version.SetValue(sAppConsent.Version.GetValue());
                rUserConsent.Authorization = BTBSwitchState.Unknow;
                rUserConsent.UpdateData();
            }
            return rUserConsent;
        }
        //-------------------------------------------------------------------------------------------------------------
        public void SetAuthorization(BTBSwitchState sStat)
        {
            Authorization = sStat;
            UpdateData();
            BTBNotificationManager.SharedInstance().PostNotification(null, NWDConsent.K_APPCONSENTS_CHANGED);
        }
        //-------------------------------------------------------------------------------------------------------------
    }
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
}
//=====================================================================================================================