//=====================================================================================================================
//
//  ideMobi 2020©
//
//=====================================================================================================================
// Define the use of Log and Benchmark only for this file!
// Add NWD_VERBOSE in scripting define symbols (Edit->Project Settings…->Player->[Choose Plateform]->Other Settings->Scripting Define Symbols)
#if NWD_VERBOSE
#if UNITY_EDITOR
#define NWD_LOG
#define NWD_BENCHMARK
#elif DEBUG
//#define NWD_LOG
//#define NWD_BENCHMARK
#endif
#else
#undef NWD_LOG
#undef NWD_BENCHMARK
#endif
//=====================================================================================================================
#if NWD_USER_IDENTITY
#if UNITY_EDITOR
using UnityEditor;
using NetWorkedData.NWDEditor;
#endif
//=====================================================================================================================
#if UNITY_EDITOR
namespace NetWorkedData.NWDEditor
{
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    public partial class NWDUserWindow : NWDBasisWindow<NWDUserWindow>
    {
        //-------------------------------------------------------------------------------------------------------------
        [MenuItem(K_PREFERENCES_MENU + "/Nickname", false, NWDEditorMenu.K_PLAYER_MANAGEMENT_INDEX + 20)]
        public static void MenuMethodNickname()
        {
            ShowWindow(typeof(NWDUserNickname));
        }
        //-------------------------------------------------------------------------------------------------------------
    }
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
}
#endif
//=====================================================================================================================
namespace NetWorkedData
{
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    public partial class NWDUserInfos : NWDBasisGameSaveDependent
    {
        //-------------------------------------------------------------------------------------------------------------
        [NWDInspectorGroupOrder("Player Informations", 3)]
        public NWDReferenceType<NWDUserNickname> Nickname { get; set; }
    }
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    /// <summary>
    /// This class create a data for user's nickname (limit by <see cref="NWDAccount"/> and <see cref="NWDGameSave"/>).
    /// It generate a <see cref="UniqueNickname"/> when synchronize on cluster with the challenge <see cref="ClusterChallenge"/> and the <see cref="Nickname"/>.
    /// </summary>
    [NWDClassMacro("NWD_USER_IDENTITY")]
    [NWDClassTrigrammeAttribute("UNN")]
    [NWDClassDescriptionAttribute("This class create a data for user's nickname (user is player for an Account + GameSave)." +
        " It generate a UniqueNickname when synchronise on the cluster with the challenge selected.")]
    [NWDClassMenuNameAttribute("User Nickname")]
#if UNITY_EDITOR
    [NWDClassClusterAttribute(1, 32)]
    [NWDWindowOwner(typeof(NWDUserWindow))]
#endif
    public partial class NWDUserNickname : NWDBasisGameSaveDependent
    {
        //-------------------------------------------------------------------------------------------------------------
        /// <summary>
        /// The <see cref="Nickname"/> filled in the form by the player in his <see cref="NWDGameSave"/>
        /// </summary>
        public string Nickname
        {
            get; set;
        }
        /// <summary>
        /// The challenge used to fill the <see cref="UniqueNickname"/>
        /// </summary>
        public NWDClusterChallenge ClusterChallenge
        {
            get; set;
        }
        /// <summary>
        /// The final unique nickname construct by <see cref="Nickname"/> and unique random string generated by the <see cref="ClusterChallenge"/>  
        /// </summary>
        [NWDNotEditable]
        public string UniqueNickname
        {
            get; set;
        }
        //-------------------------------------------------------------------------------------------------------------
    }
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
}
//=====================================================================================================================
#endif
