//=====================================================================================================================
//
//  ideMobi 2020©
//  All rights reserved by ideMobi
//
//=====================================================================================================================

#if UNITY_EDITOR
using UnityEditor;
#endif
//=====================================================================================================================
namespace NetWorkedData
{
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    public partial class NWDUserInfos : NWDBasisGameSaveDependent
    {
        //-------------------------------------------------------------------------------------------------------------
        [NWDInspectorGroupOrder("Player Informations", 3)]
        public NWDReferenceType<NWDUserNickname> Nickname { get; set; }
    }
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#if UNITY_EDITOR
    public partial class NWDUserWindow : NWDBasisWindow<NWDUserWindow>
    {
        //-------------------------------------------------------------------------------------------------------------
        [MenuItem(NWDConstants.K_MENU_BASE + "User/Nickname", false, 301)]
        public static void MenuMethodNickname()
        {
            ShowWindow(typeof(NWDUserNickname));
        }
        //-------------------------------------------------------------------------------------------------------------
    }
#endif
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    /// <summary>
    /// This class create a data for user's nickname (limit by <see cref="NWDAccount"/> and <see cref="NWDGameSave"/>).
    /// It generate a <see cref="UniqueNickname"/> when synchronize on cluster with the challenge <see cref="ClusterChallenge"/> and the <see cref="Nickname"/>.
    /// </summary>
    //[NWDClassServerSynchronizeAttribute(true)]
    [NWDClassTrigrammeAttribute("UNN")]
    [NWDClassDescriptionAttribute("This class create a data for user's nickname (user is player for an Account + GameSave)." +
        " It generate a UniqueNickname when synchronise on the cluster with the challenge selected.")]
    [NWDClassMenuNameAttribute("User Nickname")]
    [NWDClassClusterAttribute(1, 32)]
#if UNITY_EDITOR
    [NWDWindowOwner(typeof(NWDUserWindow))]
#endif
    public partial class NWDUserNickname : NWDBasisGameSaveDependent
    {
        //-------------------------------------------------------------------------------------------------------------
        /// <summary>
        /// The <see cref="Nickname"/> filled in the form by the player in his <see cref="NWDGameSave"/>
        /// </summary>
        public string Nickname
        {
            get; set;
        }
        /// <summary>
        /// The challenge used to fill the <see cref="UniqueNickname"/>
        /// </summary>
        public NWDClusterChallenge ClusterChallenge
        {
            get; set;
        }
        /// <summary>
        /// The final unique nickname construct by <see cref="Nickname"/> and unique random string generated by the <see cref="ClusterChallenge"/>  
        /// </summary>
        [NWDNotEditable]
        public string UniqueNickname
        {
            get; set;
        }
        //-------------------------------------------------------------------------------------------------------------
    }
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
}
//=====================================================================================================================