//=====================================================================================================================
//
//  ideMobi 2019©
//
//  Date		2019-4-12 18:33:59
//  Author		Kortex (Jean-François CONTART) 
//  Email		jfcontart@idemobi.com
//  Project 	NetWorkedData for Unity3D
//
//  All rights reserved by ideMobi
//
//=====================================================================================================================


using BasicToolBox;
//=====================================================================================================================
namespace NetWorkedData
{
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    public partial class NWDAccountConsent : NWDBasis<NWDAccountConsent>
    {
        //-------------------------------------------------------------------------------------------------------------
        public NWDAccountConsent()
        {
            //Debug.Log("NWDUserConsent Constructor");
        }
        //-------------------------------------------------------------------------------------------------------------
        public NWDAccountConsent(bool sInsertInNetWorkedData) : base(sInsertInNetWorkedData)
        {
            //Debug.Log("NWDUserConsent Constructor with sInsertInNetWorkedData : " + sInsertInNetWorkedData.ToString() + "");
        }
        //-------------------------------------------------------------------------------------------------------------
        public bool ConsentIsValid()
        {
            bool rReturn = true;
            NWDConsent tAppConsent = Consent.GetData();
            if (tAppConsent != null)
            {
                switch (Consent.GetData().ExpectedState)
                {
                    case BTBSwitchState.On:
                        {
                            if (Authorization != BTBSwitchState.On)
                            {
                                rReturn = false;
                                break;
                            }
                        }
                        break;
                    case BTBSwitchState.Off:
                        {
                            if (Authorization != BTBSwitchState.Off)
                            {
                                rReturn = false;
                                break;
                            }
                        }
                        break;
                    case BTBSwitchState.Unknow:
                        {
                            // no necessary spect
                        }
                        break;
                }
            }
            return rReturn;
        }
        //-------------------------------------------------------------------------------------------------------------
        public static NWDAccountConsent ForConsent(NWDConsent sAppConsent, bool sCreateIfNull = true)
        {
            NWDAccountConsent rUserConsent = null;
            foreach (NWDAccountConsent tAuthorization in NWDBasisHelper.GetReachableDatas<NWDAccountConsent>())
            {
                if (tAuthorization.Consent.GetData() == sAppConsent && tAuthorization.Version.GetValue() == sAppConsent.Version.GetValue())
                {
                    rUserConsent = tAuthorization;
                    break;
                }
            }

            if (rUserConsent == null && sCreateIfNull)
            {
                rUserConsent = NWDBasisHelper.NewData<NWDAccountConsent>();
                #if UNITY_EDITOR
                rUserConsent.InternalKey = sAppConsent.InternalKey;
                rUserConsent.InternalDescription = NWDAccountNickname.GetNickname() + " - " + sAppConsent.Version;
                #endif
                rUserConsent.Tag = NWDBasisTag.TagUserCreated; // Data generated by User-created
                rUserConsent.Consent.SetReference(sAppConsent.Reference);
                rUserConsent.Version.SetValue(sAppConsent.Version.GetValue());
                rUserConsent.Authorization = BTBSwitchState.Unknow;
                rUserConsent.UpdateData();
            }
            return rUserConsent;
        }
        //-------------------------------------------------------------------------------------------------------------
        public void SetAuthorization(BTBSwitchState sStat)
        {
            Authorization = sStat;
            UpdateData();
            BTBNotificationManager.SharedInstance().PostNotification(null, NWDConsent.K_APPCONSENTS_CHANGED);
        }
        //-------------------------------------------------------------------------------------------------------------
    }
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
}
//=====================================================================================================================