//=====================================================================================================================
//
//  ideMobi 2020©
//
//=====================================================================================================================
// Define the use of Log and Benchmark only for this file!
// Add NWD_VERBOSE in scripting define symbols (Edit->Project Settings…->Player->[Choose Plateform]->Other Settings->Scripting Define Symbols)
#if NWD_VERBOSE
#if UNITY_EDITOR
#define NWD_LOG
#define NWD_BENCHMARK
#elif DEBUG
//#define NWD_LOG
//#define NWD_BENCHMARK
#endif
#else
#undef NWD_LOG
#undef NWD_BENCHMARK
#endif
//=====================================================================================================================
#if NWD_ACCOUNT_IDENTITY

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using UnityEngine;

//=====================================================================================================================
namespace NetWorkedData
{
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    /// <summary>
    /// This class create a data for account's nickname.
    /// It generate a <see cref="UniqueNickname"/> when synchronize on cluster with the challenge <see cref="ClusterChallenge"/> and the <see cref="Nickname"/>.
    /// </summary>
    [NWDClassMacro("NWD_ACCOUNT_IDENTITY")]
    [NWDClassTrigrammeAttribute("ANN")]
    [NWDClassDescriptionAttribute("This class create a data for account's nickname." +
        " It generate a UniqueNickname when synchronise on the cluster with the challenge selected.")]
    [NWDClassMenuNameAttribute("Account Nickname")]
    [NWDClassClusterAttribute(1, 10)]
    public partial class NWDAccountNickname : NWDBasisAccountDependent
    {
        //-------------------------------------------------------------------------------------------------------------
        /// <summary>
        /// The <see cref="Nickname"/> filled in the form by the player in his account
        /// </summary>
        [NWDInspectorHeader("Informations")]
        [NWDCertified]
        public string Nickname
        {
            get; set;
        }
        /// <summary>
        /// The challenge used to fill the <see cref="UniqueNickname"/>
        /// </summary>
        public NWDClusterChallenge ClusterChallenge
        {
            get; set;
        }
        /// <summary>
        /// The final unique nickname construct by <see cref="Nickname"/> and unique random string generated by the <see cref="ClusterChallenge"/>  
        /// </summary>
        [NWDNotEditable]
        [NWDCertified]
        [NWDTooltips("Unique Nickname is determine by the server. It's guarantied as unique!")]
        public string UniqueNickname
        {
            get; set;
        }
        //-------------------------------------------------------------------------------------------------------------
    }
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
}
//=====================================================================================================================
#endif